server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 127.0.0.1
frameDelayMs: 50
datePattern: EEEE, MMMM d, yyyy
timePattern: HH:mm:ss.SSSS
networkDevices:
  - name: rtr-ge-dmarc
    x: 0
    y: 0
    z: 0
    address: 10.199.1.1
    community: 2gDtIoqrtxsS
    refreshMs: 100
    links:
      - target: sw-xe-1
        rxbOid: .1
        txbOid: .1
        speed: 1000000000
        vlid: -1