server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 127.0.0.1
frameDelayMs: 50
datePattern: EEEE, MMMM d, yyyy
timePattern: HH:mm:ss.SSSS